name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  FORCE_COLOR: 3

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.15
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Create Release PR or Publish Packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: "chore: update package versions"
          title: "chore: update package versions"
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        if: steps.changesets.outputs.published == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "A new version of {{ EVENT_PAYLOAD.repository.full_name }} was published!"
